apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  annotations:
   backstage.io/code-coverage: value
   github.com/project-slug: value
   jenkins.io/job-full-name: attestation   
   sonarqube.org/project-key: attestation
   nexus-repository-manager/docker.image-name: zirius
   nexus-repository-manager/docker.image-tag: latest
   grafana/dashboard-selector: "tags @> 'vdnzerp'"
   grafana/overview-dashboard: 'http://15.0.3.5:3000/d/e287b1f0-a9c1-4935-93c3-e8522a352e83/vdnzerp?orgId=1&kiosk'
  # This is an extra long description with Markdown
  description: |
    Test springboot app to test backstage
    - First item
    - Second item
  links:
    - url: https://github.com/karthikeyanzerp/test-backstage
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
