apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  annotations:
   backstage.io/code-coverage: value
   github.com/project-slug: value
   jenkins.io/job-full-name: attestation   
   sonarqube.org/project-key: attestation
   nexus-repository-manager/docker.image-name: zirius
   nexus-repository-manager/docker.image-tag: latest
   grafana/overview-dashboard: http://15.0.3.5:3000/d/ov0oEgdik/linux-hosts-metrics-7c-base?orgId=1&from=now-15m&to=now&refresh=5s&var-host=11.0.3.252:9100&var-job=Beta-vdnzerp
  # This is an extra long description with Markdown
  description: |
    Test springboot app to test backstage
    - First item
    - Second item
  links:
    - url: https://github.com/karthikeyanzerp/test-backstage
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
